# Generated by Django 3.2 on 2021-04-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Monster name')),
                ('how_to_breed', models.CharField(max_length=512, verbose_name='Breed Strategy')),
                ('time', models.CharField(max_length=32, verbose_name='Time')),
                ('buy_cost', models.IntegerField(verbose_name='Buy cost')),
                ('sell_cost', models.IntegerField(verbose_name='Sell cost')),
            ],
        ),
    ]
