# Generated by Django 3.2 on 2021-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Island name')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('mirror_cost', models.IntegerField(verbose_name='Mirror cost')),
                ('monsters', models.ManyToManyField(to='msm.Monster', verbose_name='Monsters')),
            ],
        ),
    ]
