# Generated by Django 3.2 on 2021-04-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0002_island'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='how_to_breed',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='time',
        ),
    ]
