# Generated by Django 3.2 on 2021-04-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0004_auto_20210420_1920'),
        ('msm', '0004_auto_20210420_2242'),
    ]

    operations = [
    ]
