# Generated by Django 3.2 on 2021-04-21 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0005_merge_0004_auto_20210420_1920_0004_auto_20210420_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='island',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='island',
            name='level',
            field=models.PositiveIntegerField(verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='island',
            name='mirror_cost',
            field=models.PositiveIntegerField(verbose_name='Mirror cost'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='default_time',
            field=models.DurationField(default=datetime.timedelta(seconds=43200), verbose_name='Default Time  to breed'),
        ),
    ]
