# Generated by Django 3.2 on 2021-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0008_monster_monster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='monster_type',
        ),
        migrations.AddField(
            model_name='monster',
            name='test',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
