# Generated by Django 3.2 on 2021-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0010_auto_20210424_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(choices=[('USUAL', 'Usual'), ('RARE', 'Rare'), ('EPIC', 'Epic')], default='USUAL', max_length=5, verbose_name='Monster type'),
        ),
    ]
