# Generated by Django 3.2 on 2021-04-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0012_auto_20210426_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingstrategy',
            name='result_monster',
        ),
        migrations.AddField(
            model_name='breedingstrategy',
            name='island',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msm.island', verbose_name='Остров'),
        ),
        migrations.AddField(
            model_name='monster',
            name='currency',
            field=models.CharField(choices=[('DIAMONDS', 'Diamonds'), ('COINS', 'Coins')], default='DIAMONDS', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='how_to_breed',
            field=models.ManyToManyField(to='msm.BreedingStrategy', verbose_name='Стратегия выведения'),
        ),
    ]
