# Generated by Django 3.2 on 2021-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0013_auto_20210427_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='slug',
            field=models.CharField(blank=True, max_length=16, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='how_to_breed',
            field=models.ManyToManyField(blank=True, to='msm.BreedingStrategy', verbose_name='Стратегия выведения'),
        ),
    ]
